# Generated by Django 5.2.17 on 2026-09-27 05:35

import django.db.models.deletion
import quorum.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('open', 'Open'), ('email', 'Email'), ('user', 'User'), ('code', 'Code')], max_length=6)),
                ('voter_key', models.CharField(max_length=64)),
                ('email_domain', models.CharField(blank=True, max_length=120)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('credits_spent', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteCode',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('batch', models.CharField(blank=True, max_length=40)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_codes', to='events.event')),
                ('redeemed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code', to='voting.voter')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(default='overall', max_length=40)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('ballot_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('net_key', models.CharField(blank=True, max_length=40)),
                ('ua_key', models.CharField(blank=True, max_length=40)),
                ('ballot_issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('void', 'Void')], default='valid', max_length=5)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='events.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='events.project')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.voter')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrityFlag',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('rule', models.CharField(max_length=40)),
                ('severity', models.CharField(default='medium', max_length=8)),
                ('subject_type', models.CharField(max_length=20)),
                ('subject_id', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=300)),
                ('evidence', models.JSONField(default=dict)),
                ('vote_ids', models.JSONField(blank=True, default=list)),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('kept', 'Kept'), ('voided', 'Voided'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('resolution_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='events.event')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='voting_inte_event_i_e95966_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'fingerprint'), name='uniq_flag_fingerprint')],
            },
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.UniqueConstraint(fields=('event', 'voter_key'), name='uniq_voter'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['event', 'project', 'created_at'], name='voting_vote_event_i_b0044c_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter', 'project', 'category'), name='uniq_vote'),
        ),
    ]
