# Generated by Django 5.2.17 on 2026-09-27 05:35

import django.db.models.deletion
import quorum.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('batch_sent', 'Batch sent'), ('midpoint', 'Midpoint nudge'), ('due_24h', '24 hours left'), ('overdue', 'Overdue'), ('custom', 'Custom')], max_length=12)),
                ('send_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('only_incomplete', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['send_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=10)),
                ('feedback_to_team', models.TextField(blank=True)),
                ('note_to_organizers', models.TextField(blank=True)),
                ('quotable', models.CharField(choices=[('no', 'Private'), ('anonymous', 'Quotable anonymously'), ('named', 'Quotable with my name')], default='no', max_length=10)),
                ('moderation', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('edited', 'Edited'), ('hidden', 'Hidden')], default='pending', max_length=10)),
                ('moderated_text', models.TextField(blank=True)),
                ('moderation_note', models.CharField(blank=True, max_length=300)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('source_scores', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('declared', 'Declared'), ('same_email', 'Same Email'), ('same_domain', 'Same Domain'), ('organizer', 'Organizer')], max_length=12)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('confirmed', 'Confirmed'), ('dismissed', 'Dismissed')], default='suggested', max_length=10)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='events.event')),
                ('judge_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='events.eventrole')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='events.team')),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('weight_bp', models.PositiveIntegerField()),
                ('scale_min', models.PositiveSmallIntegerField(default=1)),
                ('scale_max', models.PositiveSmallIntegerField(default=5)),
                ('anchors', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='events.event')),
            ],
            options={
                'ordering': ['position', 'key'],
            },
        ),
        migrations.CreateModel(
            name='JudgeBatch',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('round', models.PositiveSmallIntegerField(default=1)),
                ('kind', models.CharField(choices=[('baseline', 'Baseline'), ('focus', 'Focus'), ('tiebreak', 'Tiebreak'), ('rebalance', 'Rebalance'), ('import', 'Import')], default='baseline', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='events.event')),
                ('judge_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='events.eventrole')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('recused', 'Recused'), ('reassigned', 'Reassigned')], default='pending', max_length=12)),
                ('source', models.CharField(choices=[('algorithm', 'Algorithm'), ('manual', 'Manual'), ('import', 'Import'), ('focus', 'Focus'), ('rebalance', 'Rebalance')], default='algorithm', max_length=10)),
                ('strategy', models.CharField(blank=True, max_length=40)),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.event')),
                ('judge_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.eventrole')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.project')),
                ('reassigned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='judging.assignment')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='judging.judgebatch')),
            ],
        ),
        migrations.CreateModel(
            name='JudgingMethod',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('spec', models.JSONField()),
                ('spec_hash', models.CharField(max_length=64)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='events.event')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='PairwiseComparison',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('tie', 'Tie')], max_length=3)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='events.event')),
                ('judge_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='events.eventrole')),
                ('project_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.project')),
                ('project_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.project')),
            ],
        ),
    ]
