# Generated by Django 5.2.17 on 2026-09-27 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('judging', '0001_initial'),
        ('results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pairwisecomparison',
            name='tiebreak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='results.tiebreakround'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='events.event'),
        ),
        migrations.AddField(
            model_name='reminderdelivery',
            name='judge_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.eventrole'),
        ),
        migrations.AddField(
            model_name='reminderdelivery',
            name='reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='judging.reminder'),
        ),
        migrations.AddField(
            model_name='review',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='judging.assignment'),
        ),
        migrations.AddField(
            model_name='review',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.event'),
        ),
        migrations.AddField(
            model_name='review',
            name='judge_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.eventrole'),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.project'),
        ),
        migrations.AddField(
            model_name='reviewscore',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='judging.criterion'),
        ),
        migrations.AddField(
            model_name='reviewscore',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='judging.review'),
        ),
        migrations.AddConstraint(
            model_name='conflict',
            constraint=models.UniqueConstraint(fields=('judge_role', 'team'), name='uniq_conflict'),
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.UniqueConstraint(fields=('event', 'key'), name='uniq_criterion_key'),
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.CheckConstraint(condition=models.Q(('weight_bp__gt', 0)), name='criterion_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.CheckConstraint(condition=models.Q(('scale_min__lt', models.F('scale_max'))), name='criterion_scale_ordered'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['judge_role', 'status'], name='judging_ass_judge_r_58f5d9_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['project', 'status'], name='judging_ass_project_069f6a_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'reassigned'), _negated=True), fields=('judge_role', 'project'), name='uniq_live_assignment'),
        ),
        migrations.AddConstraint(
            model_name='judgingmethod',
            constraint=models.UniqueConstraint(fields=('event', 'version'), name='uniq_method_version'),
        ),
        migrations.AddConstraint(
            model_name='pairwisecomparison',
            constraint=models.CheckConstraint(condition=models.Q(('project_a', models.F('project_b')), _negated=True), name='pairwise_distinct'),
        ),
        migrations.AddConstraint(
            model_name='pairwisecomparison',
            constraint=models.UniqueConstraint(fields=('judge_role', 'tiebreak', 'project_a', 'project_b'), name='uniq_pairwise_per_judge'),
        ),
        migrations.AddConstraint(
            model_name='reminderdelivery',
            constraint=models.UniqueConstraint(fields=('reminder', 'judge_role'), name='uniq_reminder_delivery'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['event', 'status'], name='judging_rev_event_i_e3fdd6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['judge_role', 'status'], name='judging_rev_judge_r_4bb958_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewscore',
            constraint=models.UniqueConstraint(fields=('review', 'criterion'), name='uniq_review_criterion'),
        ),
    ]
