# Generated by Django 5.2.17 on 2026-09-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_track_pairwise'),
        ('judging', '0002_initial'),
        ('results', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pairwisecomparison',
            name='uniq_pairwise_per_judge',
        ),
        migrations.AddConstraint(
            model_name='pairwisecomparison',
            constraint=models.UniqueConstraint(fields=('judge_role', 'tiebreak', 'project_a', 'project_b'), name='uniq_pairwise_per_judge', nulls_distinct=False),
        ),
    ]
