# Generated by Django 5.2.17 on 2026-09-27 05:35

import quorum.core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SigningKey',
            fields=[
                ('key_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('public_key_b64', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_job_status_38dcf0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('target', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('dead', 'Dead')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(auto_now_add=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='core_outbox_status_008ef8_idx')],
            },
        ),
        migrations.CreateModel(
            name='RateBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['window_start'], name='core_ratebu_window__90880f_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'window_start'), name='uniq_rate_bucket')],
            },
        ),
    ]
