# Generated by Django 5.2.17 on 2026-09-27 05:35

import django.db.models.deletion
import quorum.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCheckpoint',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('seq', models.BigIntegerField()),
                ('head', models.CharField(max_length=64)),
                ('reason', models.CharField(max_length=80)),
                ('payload', models.TextField()),
                ('signature', models.CharField(max_length=128)),
                ('key_id', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('actor_label', models.CharField(blank=True, max_length=160)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(max_length=48)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(max_length=400)),
                ('data', models.JSONField(default=dict)),
                ('prev_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('actor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.event')),
            ],
            options={
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['event', 'seq'], name='audit_audit_event_i_7ed5e8_idx'), models.Index(fields=['event', 'action'], name='audit_audit_event_i_69ab84_idx')],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('participant', 'Participant'), ('winner', 'Winner'), ('judge_protocol', 'Judge Protocol')], max_length=16)),
                ('serial', models.CharField(max_length=40)),
                ('payload', models.TextField()),
                ('signature', models.CharField(max_length=128)),
                ('key_id', models.CharField(max_length=32)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'kind', 'serial'), name='uniq_certificate_serial'), models.UniqueConstraint(fields=('event', 'kind', 'user'), name='uniq_certificate_per_user')],
            },
        ),
    ]
