# Generated by Django 5.2.17 on 2026-09-27 05:35

import django.db.models.deletion
import quorum.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('ref', models.SlugField(max_length=40, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description_md', models.TextField(blank=True)),
                ('rules_md', models.TextField(blank=True)),
                ('is_listed', models.BooleanField(default=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('registration_opens_at', models.DateTimeField()),
                ('submissions_open_at', models.DateTimeField()),
                ('submissions_close_at', models.DateTimeField()),
                ('grace_seconds', models.PositiveIntegerField(default=0)),
                ('judging_opens_at', models.DateTimeField()),
                ('judging_closes_at', models.DateTimeField()),
                ('voting_opens_at', models.DateTimeField(blank=True, null=True)),
                ('voting_closes_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_released_at', models.DateTimeField(blank=True, null=True)),
                ('results_published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('draft', 'Draft'), ('registration', 'Registration'), ('submissions', 'Submissions open'), ('closed', 'Submissions closed'), ('judging', 'Judging'), ('focus', 'Focus round'), ('deliberation', 'Deliberation'), ('locked', 'Results locked'), ('published', 'Results published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('team_size_max', models.PositiveSmallIntegerField(default=4)),
                ('reviews_per_project', models.PositiveSmallIntegerField(default=3)),
                ('batch_size', models.PositiveSmallIntegerField(default=12)),
                ('min_feedback_chars', models.PositiveSmallIntegerField(default=80)),
                ('focus_budget_pct', models.PositiveSmallIntegerField(default=15)),
                ('prize_positions', models.PositiveSmallIntegerField(default=3)),
                ('voting_mode', models.CharField(choices=[('off', 'Off'), ('open', 'Open link'), ('email', 'Email-verified'), ('authenticated', 'Signed-in accounts'), ('code', 'One-time codes')], default='off', max_length=16)),
                ('votes_per_voter', models.PositiveSmallIntegerField(default=3)),
                ('quadratic_voting', models.BooleanField(default=False)),
                ('rank_display', models.CharField(choices=[('exact', 'Exact rank'), ('band', 'Rank band'), ('none', 'No rank')], default='exact', max_length=8)),
                ('auto_approve_feedback', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submissions_close_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=200)),
                ('help', models.CharField(blank=True, max_length=300)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('long_text', 'Long Text'), ('url', 'Url'), ('choice', 'Choice'), ('bool', 'Bool')], default='text', max_length=10)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.event')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='EventRole',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('organizer', 'Organizer'), ('judge', 'Judge'), ('participant', 'Participant')], max_length=12)),
                ('ref', models.CharField(blank=True, max_length=40)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('description_md', models.TextField(blank=True)),
                ('description_html', models.TextField(blank=True)),
                ('thumbnail', models.CharField(blank=True, max_length=200)),
                ('demo_video_url', models.URLField(blank=True, max_length=400)),
                ('repo_url', models.URLField(blank=True, max_length=400)),
                ('live_url', models.URLField(blank=True, max_length=400)),
                ('declared_commit_sha', models.CharField(blank=True, max_length=64)),
                ('tech_tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('withdrawn', 'Withdrawn'), ('disqualified', 'Disqualified')], default='draft', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='events.project')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='events.event')),
            ],
            options={
                'ordering': ['submitted_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityItem',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('duplicate', 'Duplicate'), ('missing_field', 'Missing Field'), ('late_attempt', 'Late Attempt'), ('team_size', 'Team Size'), ('conflict', 'Conflict')], max_length=16)),
                ('details', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='open', max_length=10)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_items', to='events.event')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_items', to='events.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('body_html', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('hidden_reason', models.CharField(blank=True, max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('hidden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='events.project')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='events.project')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='events.customquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.project')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='events.project')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=80)),
                ('invite_code_hash', models.CharField(blank=True, max_length=64)),
                ('invite_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.event')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='events.team'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=8)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='events.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='events.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='events.event')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='events.track'),
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('places', models.PositiveSmallIntegerField(default=1)),
                ('kind', models.CharField(choices=[('judged', 'Judged'), ('community', 'Community')], default='judged', max_length=10)),
                ('value_text', models.CharField(blank=True, max_length=80)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.event')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.track')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JudgeTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_tracks', to='events.eventrole')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_links', to='events.track')),
            ],
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('submissions_open_at__lte', models.F('submissions_close_at'))), name='event_submission_window_ordered'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('judging_opens_at__lte', models.F('judging_closes_at'))), name='event_judging_window_ordered'),
        ),
        migrations.AddConstraint(
            model_name='customquestion',
            constraint=models.UniqueConstraint(fields=('event', 'ref'), name='uniq_question_ref'),
        ),
        migrations.AddIndex(
            model_name='eventrole',
            index=models.Index(fields=['event', 'role'], name='events_even_event_i_0df1f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventrole',
            constraint=models.UniqueConstraint(fields=('event', 'user', 'role'), name='uniq_event_user_role'),
        ),
        migrations.AddConstraint(
            model_name='eventrole',
            constraint=models.UniqueConstraint(condition=models.Q(('ref', ''), _negated=True), fields=('event', 'ref'), name='uniq_event_role_ref'),
        ),
        migrations.AddConstraint(
            model_name='projectanswer',
            constraint=models.UniqueConstraint(fields=('project', 'question'), name='uniq_answer'),
        ),
        migrations.AddConstraint(
            model_name='projectrevision',
            constraint=models.UniqueConstraint(fields=('project', 'version'), name='uniq_revision'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('event', 'ref'), name='uniq_team_ref'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='uniq_team_name'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='uniq_one_team_per_event'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('event', 'ref'), name='uniq_track_ref'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['event', 'status', 'track'], name='events_proj_event_i_ab9642_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('event', 'ref'), name='uniq_project_ref'),
        ),
        migrations.AddConstraint(
            model_name='judgetrack',
            constraint=models.UniqueConstraint(fields=('event_role', 'track'), name='uniq_judge_track'),
        ),
    ]
