# Generated by Django 5.2.17 on 2026-09-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='uniq_team_name',
        ),
    ]
