# Generated by Django 5.2.17 on 2026-09-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_team_names_not_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='pairwise',
            field=models.BooleanField(default=False),
        ),
    ]
