# Generated by Django 5.2.17 on 2026-09-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=24)),
                ('object_id', models.CharField(max_length=64)),
                ('content_hash', models.CharField(max_length=64)),
                ('vector', models.BinaryField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'content_hash'], name='intelligenc_kind_e7bd6e_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'object_id'), name='uniq_embedding_object')],
            },
        ),
    ]
