# Generated by Django 5.2.17 on 2026-09-27 05:35

import django.db.models.deletion
import quorum.core.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('fixtures', 'DOGFOOD fixtures JSON'), ('bundle', 'Quorum bundle JSON'), ('devpost_csv', 'Devpost CSV export'), ('unstop_csv', 'Unstop CSV export'), ('generic_csv', 'Any CSV (map columns)')], max_length=12)),
                ('filename', models.CharField(max_length=200)),
                ('file_sha256', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('dry_run', 'Dry Run'), ('committed', 'Committed'), ('failed', 'Failed')], default='dry_run', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=quorum.core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=400)),
                ('secret', models.CharField(max_length=64)),
                ('topics', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_status', models.CharField(blank=True, max_length=80)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='events.event')),
            ],
        ),
    ]
