#!/usr/bin/env python3
"""Generate docs/proof/: the normalization proof, run with the product's own engine.

1. The real fixture: raw vs calibrated ranking, what moved and why, the signal check.
2. Simulation on the fixture's exact design (123 judge-project pairs, 3 integer criteria,
   jdg_07 flat) with known truth: Kendall tau of raw mean, per-judge z-score and the
   calibrated estimator, paired, under increasing judge leniency spread.
3. Assignment design: disjoint panels vs overlap-aware assignment.

    python3 tools/generate_proof.py [--sims 300]
"""

import argparse
import json
import random
import statistics as st
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from engine.assign import assign, assign_disjoint_panels  # noqa: E402
from engine.calibrate import fit_judge_effects  # noqa: E402
from engine.compare import kendall_tau_b, raw_scores, zscore_scores  # noqa: E402
from engine.fixtures import from_dogfood_fixture  # noqa: E402
from engine.pipeline import compute  # noqa: E402

FIX = json.loads((ROOT / "fixtures.json").read_text())
INP, LOG = from_dogfood_fixture(FIX)
DESIGN = INP["reviews"]
C = ["functionality", "quality", "innovation"]
W = {c: 1 for c in C}
OUT = ROOT / "docs" / "proof"


def simulate(seed, lsd, design=DESIGN, noise=0.9, flat="jdg_07"):
    rng = random.Random(seed)
    ps = sorted({r["project"] for r in design})
    js = sorted({r["judge"] for r in design})
    th = {p: rng.gauss(0, 0.45) for p in ps}
    d = {(p, c): rng.gauss(0, 0.3) for p in ps for c in C}
    b = {j: rng.gauss(0, lsd) for j in js}
    rv = [{"judge": r["judge"], "project": r["project"], "criteria": {
        c: 3.0 if r["judge"] == flat else float(min(5, max(1, round(3.4 + th[r["project"]] + d[(r["project"], c)]
                                                                     + b[r["judge"]] + rng.gauss(0, noise)))))
        for c in C}} for r in design]
    return {p: th[p] + st.mean(d[(p, c)] for c in C) for p in ps}, rv


def tau(truth, sc, seed):
    rng = random.Random(seed)
    ps = sorted(truth)
    j = {p: rng.random() * 1e-9 for p in ps}
    return kendall_tau_b([truth[p] for p in ps], [sc[p] + j[p] for p in ps])


def top1(truth, sc):
    return max(truth, key=truth.get) == max(sc, key=sc.get)


def ci(xs):
    return 1.96 * st.stdev(xs) / len(xs) ** 0.5


def svg_bars(rows, title, fname):
    """rows: [(label, value, err)] -> horizontal bar chart centred on 0."""
    W_, H = 640, 40 + 34 * len(rows)
    vmax = max(abs(v) + e for _, v, e in rows) or 1
    x0 = 320
    sx = lambda v: x0 + 260 * v / vmax
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W_} {H}" font-family="system-ui,sans-serif" font-size="12">',
           f'<text x="10" y="20" font-weight="700">{title}</text>',
           f'<line x1="{x0}" y1="30" x2="{x0}" y2="{H - 5}" stroke="#999"/>']
    for i, (label, v, e) in enumerate(rows):
        y = 40 + 34 * i
        a, b2 = sorted((sx(0), sx(v)))
        out.append(f'<rect x="{a:.1f}" y="{y}" width="{max(b2 - a, 1):.1f}" height="18" fill="{"#1f7a4d" if v >= 0 else "#b3261e"}"/>')
        out.append(f'<line x1="{sx(v - e):.1f}" y1="{y + 9}" x2="{sx(v + e):.1f}" y2="{y + 9}" stroke="#333"/>')
        out.append(f'<text x="10" y="{y + 13}">{label}</text>')
        out.append(f'<text x="{max(sx(v), x0) + 8:.1f}" y="{y + 13}">{v:+.3f}</text>')
    out.append("</svg>")
    (OUT / fname).write_text("\n".join(out))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sims", type=int, default=300)
    n = ap.parse_args().sims
    OUT.mkdir(parents=True, exist_ok=True)
    t0 = time.time()
    md = ["# Normalization proof", "",
          f"Generated by `tools/generate_proof.py` with the product engine (`src/engine`), {n} simulations per "
          "scenario. Every number here can be reproduced with one command and nothing but Python.", ""]
    # 1. the real fixture
    res = compute(INP, heavy=False)
    sig = res["signal"]
    md += ["## 1. The fixture itself", "",
           f"- Duplicate merged: {LOG['duplicates'][0]['superseded'][0]} → {LOG['duplicates'][0]['canonical']}; "
           f"{len(LOG['retest'])} judges scored both copies, and disagreed with themselves by "
           + ", ".join(f"{abs(sum(c['scores'][0].values()) - sum(c['scores'][1].values())) / 3:.2f}" for c in LOG["retest"])
           + " points (a free test-retest noise measurement).",
           f"- Flat judge: {', '.join(res['flat_judges'])} (identical scores on every criterion of every review) → weight 0.",
           f"- Shrinkage chosen by REML: k = {res['k']:.2f} (judge offsets are barely identifiable in this data).",
           f"- **Signal check: ICC(1) = {sig['icc1']:.3f}, permutation p = {sig['p_value']:.2f}.** The judges agree "
           "about which projects are better no more than chance would. **No method can recover a ranking from these "
           "scores**; the honest output is a list of ties, and Quorum says so on the results page.", "",
           "| Rank | Project | n | Raw | Calibrated | ±SE | Plausible ranks (90%) | P(top 3) | vs raw |",
           "|---:|---|---:|---:|---:|---:|---|---:|---:|"]
    titles = {p["id"]: p["title"] for p in FIX["projects"]}
    for e in res["entries"][:12]:
        md.append(f"| {e['rank']} | {titles[e['project']]} | {e['n_reviews']} | {e['raw']:.2f} | {e['calibrated']:.2f} | "
                  f"{e['se']:.2f} | {e['rank_lo']}–{e['rank_hi']} | {e['p_prize']:.0%} | {e['move_vs_raw']:+d} |")
    moved = sorted(res["entries"], key=lambda e: -abs(e["move_vs_raw"]))[:5]
    md += ["", "Largest moves, explained exactly (raw mean + one line per judge = calibrated score):", ""]
    for e in moved:
        x = res["explanations"][e["project"]]
        md.append(f"- **{titles[e['project']]}** ({e['raw_rank']} → {e['rank']}): raw {x['raw_mean']:.3f} "
                  + " ".join(f"· {l['judge']} ({l['label']}) {l['contribution']:+.3f}" for l in x["lines"])
                  + f" = **{x['final']:.3f}**")
    # 2. simulations on the fixture's design
    md += ["", "## 2. Simulation on the fixture's exact design", "",
           "Truth is known. Each review is `round(3.4 + quality + judge leniency + noise)`, clipped to 1–5, on 3 "
           "criteria, over the fixture's 123 judge–project pairs, with jdg_07 always giving 3. Ties in any method's "
           "scores are broken identically at random (Kendall's τ-b otherwise rewards the exact ties of raw integer "
           "means). Entries are paired differences against the raw mean, with 95% intervals.", "",
           "| Judge leniency spread (sd) | Raw τ | z-score − raw | **Calibrated − raw** | P(true #1 ranked #1): raw / z / calibrated |",
           "|---|---:|---:|---:|---|"]
    bars = []
    for lsd in (0.0, 0.2, 0.4, 0.6, 0.8):
        d_cal, d_z, raws, t1 = [], [], [], [0, 0, 0]
        for s in range(n):
            truth, rv = simulate(s, lsd)
            cal = fit_judge_effects(rv, W)["score"]
            raw = raw_scores(rv, W)
            z, _ = zscore_scores(rv, W)
            tr, tz, tc = tau(truth, raw, s), tau(truth, z, s), tau(truth, cal, s)
            raws.append(tr)
            d_cal.append(tc - tr)
            d_z.append(tz - tr)
            t1[0] += top1(truth, raw)
            t1[1] += top1(truth, z)
            t1[2] += top1(truth, cal)
        md.append(f"| {lsd} | {st.mean(raws):.3f} | {st.mean(d_z):+.3f} ± {ci(d_z):.3f} | **{st.mean(d_cal):+.3f} ± {ci(d_cal):.3f}** | "
                  f"{t1[0] / n:.0%} / {t1[1] / n:.0%} / {t1[2] / n:.0%} |")
        bars.append((f"leniency sd {lsd}: calibrated", st.mean(d_cal), ci(d_cal)))
        bars.append((f"leniency sd {lsd}: z-score", st.mean(d_z), ci(d_z)))
    svg_bars(bars, "Kendall tau gain vs raw mean (fixture design)", "gain.svg")
    md += ["", "![gain vs raw mean](gain.svg)", "",
           "Reading it: when judges differ in leniency, calibration recovers the true order better than the raw mean, "
           "and the gain grows with the spread. When they do not, it costs nothing measurable, because REML chooses a "
           "large k and the estimator collapses to the raw mean. Per-judge z-scores are worse than calibration in every "
           "scenario: they are undefined for single-review and flat judges, and they punish projects that a judge happened "
           "to review alongside strong ones."]
    # 3. design
    projects = [{"id": f"p{i}", "track": f"t{i % 8}"} for i in range(40)]
    judges = [{"id": f"j{i}", "tracks": [f"t{i % 8}", f"t{(i + 3) % 8}"]} for i in range(30)]
    rows = {}
    for name, fn in (("disjoint panels", lambda s: assign_disjoint_panels(projects, [dict(j, tracks=None) for j in judges], 3, s)["assignment"]),
                     ("overlap-aware (Quorum)", lambda s: assign(projects, judges, 3, seed=s)["assignment"])):
        g = []
        for s in range(max(60, n // 3)):
            design = [{"judge": j, "project": p} for p, js in fn(s).items() for j in js]
            truth, rv = simulate(s, 0.5, design=design, flat=None)
            g.append(tau(truth, fit_judge_effects(rv, W)["score"], s) - tau(truth, raw_scores(rv, W), s))
        rows[name] = (st.mean(g), ci(g))
    md += ["", "## 3. Assignment is part of the measurement", "",
           "40 projects, 30 judges, 3 reviews each, leniency sd 0.5. The same calibration, two assignment designs:", "",
           "| Design | Calibrated − raw (τ) |", "|---|---:|"]
    md += [f"| {k} | {v[0]:+.3f} ± {v[1]:.3f} |" for k, v in rows.items()]
    md += ["", "With disjoint panels the gain is exactly zero, and not by chance: when every project in a panel was "
               "reviewed by the same judges, each judge's offset shifts all of that panel's projects equally, so the "
               "calibrated score is provably identical to the raw mean. A harsh panel and a weak batch of projects are "
               "indistinguishable. When batches overlap, leniency becomes measurable. That is why Quorum's assignment "
               "planner maximises overlap and reports the judge graph's connectivity before anything is committed.",
           "", "## 4. Focus rounds and tie-breaks", "",
           "The allocation experiments (400 seeds, ICC ≈ 0.31) are in `research/math/results_adaptive.txt`. With the same "
           "120 reviews, 2 each plus two targeted rounds of 20 picked the true winner 43.5% of the time vs 33.5% for "
           "uniform 3 each; adding the pairwise tie-break raised it to 53.5% (persistent-impression noise, the "
           "conservative case).", "", f"_Generated in {time.time() - t0:.0f}s._"]
    (OUT / "README.md").write_text("\n".join(md) + "\n")
    print(f"wrote {OUT / 'README.md'} ({time.time() - t0:.0f}s)")


if __name__ == "__main__":
    main()
